# Generated by Django 4.2.6 on 2023-11-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='la direccion'),
        ),
    ]
