# Generated by Django 4.2.6 on 2023-11-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_alter_clientes_tfno_alter_pedidos_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('direccion', models.DateField(verbose_name='fecha')),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
