# Generated by Django 4.2.6 on 2023-11-12 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_occidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_area', models.CharField(max_length=50)),
                ('descripcion', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField(max_length=3)),
                ('dui', models.PositiveIntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField(max_length=3)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.area')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField()),
                ('monto', models.FloatField()),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.cliente')),
                ('empleadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.empleado')),
            ],
        ),
    ]
